import { NextRequest, NextResponse } from "next/server";
import { getAccessUser, getDb, runtime } from "@/db";

function row(r: Record<string, unknown>) { return { id:r.id, departure:r.departure, arrival:r.arrival, startDate:r.start_date, startTime:r.start_time, endDate:r.end_date, endTime:r.end_time, airline:r.airline, targetPrice:r.target_price, threshold:r.threshold, airlineTargetPrice:r.airline_target_price, airlineThreshold:r.airline_threshold, email:r.email, active:r.active }; }
function automated(req: NextRequest) { const token=req.headers.get("authorization")?.replace(/^Bearer /,""); return Boolean(runtime.MONITOR_API_KEY && token===runtime.MONITOR_API_KEY); }
async function userEmail(req: NextRequest) { const email=req.headers.get("oai-authenticated-user-email")?.toLowerCase(); return email && await getAccessUser(email) ? email : null; }
function valid(b: Record<string, unknown>) { const start=`${b.startDate}T${b.startTime}`; const end=`${b.endDate}T${b.endTime}`; return /^[A-Z]{3}$/.test(String(b.departure)) && /^[A-Z]{3}$/.test(String(b.arrival)) && /^[A-Z0-9]{2}$/.test(String(b.airline)) && /^([01]\d|2[0-3]):[0-5]\d$/.test(String(b.startTime)) && /^([01]\d|2[0-3]):[0-5]\d$/.test(String(b.endTime)) && /^\S+@\S+\.\S+$/.test(String(b.email)) && start <= end && Number(b.targetPrice) >= 1 && Number(b.airlineTargetPrice) >= 1; }
export async function GET(req: NextRequest) { const email=await userEmail(req); if (!email && !automated(req)) return NextResponse.json({error:"Unauthorized"},{status:401}); const db=await getDb(); const query=automated(req)?db.prepare("SELECT * FROM monitors WHERE active=1 ORDER BY updated_at DESC"):db.prepare("SELECT * FROM monitors WHERE active=1 AND owner_email=? ORDER BY updated_at DESC").bind(email); const {results}=await query.all(); return NextResponse.json(results.map(r=>row(r as Record<string,unknown>))); }
export async function POST(req: NextRequest) { const owner=await userEmail(req); if (!owner) return NextResponse.json({error:"Unauthorized"},{status:401}); const b=await req.json(); if(!valid(b)) return NextResponse.json({error:"Invalid monitor"},{status:400}); const db=await getDb(); await db.prepare("INSERT INTO monitors (departure,arrival,start_date,start_time,end_date,end_time,airline,target_price,threshold,airline_target_price,airline_threshold,email,owner_email,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(b.departure,b.arrival,b.startDate,b.startTime,b.endDate,b.endTime,b.airline,b.targetPrice,b.targetPrice,b.airlineTargetPrice,b.airlineTargetPrice,b.email,owner,new Date().toISOString()).run(); return NextResponse.json({ok:true},{status:201}); }
export async function PUT(req: NextRequest) { const owner=await userEmail(req); if (!owner) return NextResponse.json({error:"Unauthorized"},{status:401}); const b=await req.json(); if(!valid(b)||!Number.isInteger(Number(b.id))) return NextResponse.json({error:"Invalid monitor"},{status:400}); const db=await getDb(); const result=await db.prepare("UPDATE monitors SET departure=?, arrival=?, start_date=?, start_time=?, end_date=?, end_time=?, airline=?, threshold=CASE WHEN target_price<>? THEN ? ELSE threshold END, target_price=?, airline_threshold=CASE WHEN airline_target_price<>? OR airline<>? THEN ? ELSE airline_threshold END, airline_target_price=?, email=?, updated_at=? WHERE id=? AND owner_email=?").bind(b.departure,b.arrival,b.startDate,b.startTime,b.endDate,b.endTime,b.airline,b.targetPrice,b.targetPrice,b.targetPrice,b.airlineTargetPrice,b.airline,b.airlineTargetPrice,b.airlineTargetPrice,b.email,new Date().toISOString(),b.id,owner).run(); return NextResponse.json({ok:result.meta.changes===1},{status:result.meta.changes===1?200:404}); }
export async function PATCH(req: NextRequest) { if (!automated(req)) return NextResponse.json({error:"Unauthorized"},{status:401}); const b=await req.json(); const db=await getDb(); const column=b.thresholdType==="airline"?"airline_threshold":"threshold"; await db.prepare(`UPDATE monitors SET ${column}=?, updated_at=? WHERE id=? AND ? < ${column}`).bind(b.threshold,new Date().toISOString(),b.id,b.threshold).run(); return NextResponse.json({ok:true}); }
export async function DELETE(req: NextRequest) { const owner=await userEmail(req); if (!owner) return NextResponse.json({error:"Unauthorized"},{status:401}); const db=await getDb(); const id=Number(req.nextUrl.searchParams.get("id")); const result=await db.prepare("DELETE FROM monitors WHERE id=? AND owner_email=?").bind(id,owner).run(); return NextResponse.json({ok:result.meta.changes===1},{status:result.meta.changes===1?200:404}); }
