import { NextRequest, NextResponse } from "next/server";
import { getDb, runtime } from "@/db";

function row(r: Record<string, unknown>) { return { id:r.id, departure:r.departure, arrival:r.arrival, startDate:r.start_date, endDate:r.end_date, targetPrice:r.target_price, threshold:r.threshold, email:r.email, active:r.active }; }
function automated(req: NextRequest) { const token=req.headers.get("authorization")?.replace(/^Bearer /,""); return Boolean(runtime.MONITOR_API_KEY && token===runtime.MONITOR_API_KEY); }
function userEmail(req: NextRequest) { return req.headers.get("oai-authenticated-user-email"); }
function valid(b: Record<string, unknown>) { return /^[A-Z]{3}$/.test(String(b.departure)) && /^[A-Z]{3}$/.test(String(b.arrival)) && /^\S+@\S+\.\S+$/.test(String(b.email)) && String(b.startDate) <= String(b.endDate) && Number(b.targetPrice) >= 1; }
export async function GET(req: NextRequest) { const email=userEmail(req); if (!email && !automated(req)) return NextResponse.json({error:"Unauthorized"},{status:401}); const db=await getDb(); const query=automated(req)?db.prepare("SELECT * FROM monitors WHERE active=1 ORDER BY updated_at DESC"):db.prepare("SELECT * FROM monitors WHERE active=1 AND owner_email=? ORDER BY updated_at DESC").bind(email); const {results}=await query.all(); return NextResponse.json(results.map(r=>row(r as Record<string,unknown>))); }
export async function POST(req: NextRequest) { const owner=userEmail(req); if (!owner) return NextResponse.json({error:"Unauthorized"},{status:401}); const b=await req.json(); if(!valid(b)) return NextResponse.json({error:"Invalid monitor"},{status:400}); const db=await getDb(); await db.prepare("INSERT INTO monitors (departure,arrival,start_date,end_date,target_price,threshold,email,owner_email,updated_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(b.departure,b.arrival,b.startDate,b.endDate,b.targetPrice,b.targetPrice,b.email,owner,new Date().toISOString()).run(); return NextResponse.json({ok:true},{status:201}); }
export async function PUT(req: NextRequest) { const owner=userEmail(req); if (!owner) return NextResponse.json({error:"Unauthorized"},{status:401}); const b=await req.json(); if(!valid(b)||!Number.isInteger(Number(b.id))) return NextResponse.json({error:"Invalid monitor"},{status:400}); const db=await getDb(); const result=await db.prepare("UPDATE monitors SET departure=?, arrival=?, start_date=?, end_date=?, threshold=CASE WHEN target_price<>? THEN ? ELSE threshold END, target_price=?, email=?, updated_at=? WHERE id=? AND owner_email=?").bind(b.departure,b.arrival,b.startDate,b.endDate,b.targetPrice,b.targetPrice,b.targetPrice,b.email,new Date().toISOString(),b.id,owner).run(); return NextResponse.json({ok:result.meta.changes===1},{status:result.meta.changes===1?200:404}); }
export async function PATCH(req: NextRequest) { if (!automated(req)) return NextResponse.json({error:"Unauthorized"},{status:401}); const b=await req.json(); const db=await getDb(); await db.prepare("UPDATE monitors SET threshold=?, updated_at=? WHERE id=? AND ? < threshold").bind(b.threshold,new Date().toISOString(),b.id,b.threshold).run(); return NextResponse.json({ok:true}); }
export async function DELETE(req: NextRequest) { const owner=userEmail(req); if (!owner) return NextResponse.json({error:"Unauthorized"},{status:401}); const db=await getDb(); const id=Number(req.nextUrl.searchParams.get("id")); const result=await db.prepare("DELETE FROM monitors WHERE id=? AND owner_email=?").bind(id,owner).run(); return NextResponse.json({ok:result.meta.changes===1},{status:result.meta.changes===1?200:404}); }
